version: '1.0'
services:
  app:
    container_name: "application-server"
    image: "linuxserver/libreoffice:7.2.2.2-r2-ls58"
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
volumes:
  data: 